# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BuffetFoodFinder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BuffetFoodFinder
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'

  # react-native-google-place-picker dependencies
  pod 'GooglePlacePicker', '= 2.0.1'
  pod 'GooglePlaces', '= 2.0.1'
  pod 'GoogleMaps', '= 2.0.1'
  
  # for android compile "com.google.firebase:firebase-auth:11.6.0"
  #https://blog.benestudio.co/kickstart-your-react-native-app-with-firebase-authentication-tutorial-2-ca70577875eb
  pod 'Firebase/Auth'
  # target 'BuffetFoodFinder-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
  #
  # target 'BuffetFoodFinderTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

# target 'BuffetFoodFinder-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for BuffetFoodFinder-tvOS
#
#   target 'BuffetFoodFinder-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
